# Docker compose allows to specify and start several containers
version: "2"
services:
    cnag:
      build: .
      image: cnag:1.0.1-alpine
      environment:
      - PORT=9090
      ports:
      - "9090:9090"